// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260506070052_FleetStrengthFieldMapping")]
    partial class FleetStrengthFieldMapping
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("backend.Models.Core.BillClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Comments")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedById")
                        .HasColumnType("integer");

                    b.Property<string>("FirmName")
                        .HasColumnType("text");

                    b.Property<bool>("ForwardedToTreasury")
                        .HasColumnType("boolean");

                    b.Property<string>("SanctionAuthority")
                        .HasColumnType("text");

                    b.Property<DateTime?>("SanctionOrderDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SanctionOrderNo")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("SubVoucherDescription")
                        .HasColumnType("text");

                    b.Property<string>("SubVoucherNo")
                        .HasColumnType("text");

                    b.Property<decimal>("Tax")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<int?>("VehicleId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("VerifiedById")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("VehicleId");

                    b.HasIndex("VerifiedById");

                    b.ToTable("BillClaims");
                });

            modelBuilder.Entity("backend.Models.Core.ContractualBill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("BillDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("BillNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("BillPeriodFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("BillPeriodTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ClaimId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedById")
                        .HasColumnType("integer");

                    b.Property<string>("DdoCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("VehicleNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("ClaimId");

                    b.HasIndex("CreatedById");

                    b.ToTable("ContractualBills");
                });

            modelBuilder.Entity("backend.Models.Core.FuelBill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("BillDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("BillNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("ClaimId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedById")
                        .HasColumnType("integer");

                    b.Property<decimal>("FuelQuantity")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("NocExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NocFile")
                        .HasColumnType("text");

                    b.Property<DateTime?>("NocIssueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("OdometerReading")
                        .HasColumnType("integer");

                    b.Property<string>("SanctionPermissionFile")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("VehicleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClaimId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("VehicleId");

                    b.ToTable("FuelBills");
                });

            modelBuilder.Entity("backend.Models.Core.HiredVehicleBill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("BillDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("BillNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("ClaimId")
                        .HasColumnType("integer");

                    b.Property<string>("ContractorName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ContractorPhone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedById")
                        .HasColumnType("integer");

                    b.Property<DateTime>("HiredFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("HiredTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("KmCovered")
                        .HasColumnType("integer");

                    b.Property<int>("NoOfVehicles")
                        .HasColumnType("integer");

                    b.Property<string>("OfficeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("VehicleNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("VehicleType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("ClaimId");

                    b.HasIndex("CreatedById");

                    b.ToTable("HiredVehicleBills");
                });

            modelBuilder.Entity("backend.Models.Core.InventoryAllotment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AllotmentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("AllottedByUserId")
                        .HasColumnType("integer");

                    b.Property<int>("InventoryItemId")
                        .HasColumnType("integer");

                    b.Property<string>("OdometerReading")
                        .HasColumnType("text");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<string>("Remarks")
                        .HasColumnType("text");

                    b.Property<int>("VehicleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AllottedByUserId");

                    b.HasIndex("InventoryItemId");

                    b.HasIndex("VehicleId");

                    b.ToTable("InventoryAllotments");
                });

            modelBuilder.Entity("backend.Models.Core.InventoryItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("InventoryItems");
                });

            modelBuilder.Entity("backend.Models.Core.MaintenanceBill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("BillDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("BillNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("ClaimId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedById")
                        .HasColumnType("integer");

                    b.Property<string>("Details")
                        .HasColumnType("text");

                    b.Property<string>("MaintenanceType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("OdometerReading")
                        .HasColumnType("integer");

                    b.Property<string>("SanctionPermissionFile")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("VehicleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClaimId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("VehicleId");

                    b.ToTable("MaintenanceBills");
                });

            modelBuilder.Entity("backend.Models.Core.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Drawing & Disbursing Officer (Maker)",
                            Name = "DDO"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Administrator (Checker)",
                            Name = "ADMN"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Nodal Officer (Verifier)",
                            Name = "NDOF"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Secretary",
                            Name = "SEC"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Head of Department",
                            Name = "HOD"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "District Collector",
                            Name = "DCL"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Finance Department",
                            Name = "FD"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Petrol Pump Officer",
                            Name = "PPOF"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Guest User (OTP Login)",
                            Name = "GUEST"
                        });
                });

            modelBuilder.Entity("backend.Models.Core.StockTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("BillDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("BillNumber")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("InventoryItemId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<string>("Remarks")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("InventoryItemId");

                    b.HasIndex("UserId");

                    b.ToTable("StockTransactions");
                });

            modelBuilder.Entity("backend.Models.Core.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("UserId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedDate");

                    b.Property<string>("DDOCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("DepartmentDeptId")
                        .HasColumnType("integer");

                    b.Property<int?>("DeptId")
                        .HasColumnType("integer")
                        .HasColumnName("DeptId");

                    b.Property<int?>("DistrictId")
                        .HasColumnType("integer");

                    b.Property<string>("EmailId")
                        .HasColumnType("text")
                        .HasColumnName("EmailId");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("Enabled");

                    b.Property<int>("FailedAttempts")
                        .HasColumnType("integer");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<bool>("IsGuest")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsNonTreasuryDDO")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LockUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ManagedDdos")
                        .HasColumnType("text");

                    b.Property<string>("MiddleName")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNo")
                        .HasColumnType("text")
                        .HasColumnName("PhoneNo");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.HasIndex("DepartmentDeptId");

                    b.HasIndex("DistrictId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("backend.Models.Core.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("backend.Models.Core.VehicleCondemnation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("AuctionAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("AuctionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AuctionStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CondemnationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CondemnationOrderNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CondemnationOrderPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("VehicleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("VehicleId");

                    b.ToTable("VehicleCondemnations");
                });

            modelBuilder.Entity("backend.Models.Core.VehicleInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AllocationType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContractorContactNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContractorName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrentStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DDOCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("integer");

                    b.Property<int?>("DesignationId")
                        .HasColumnType("integer");

                    b.Property<string>("DriverContactNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DriverName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DriverType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EngineChasisNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FdApprovalPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FleetStrengthLetterPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FuelUsed")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HRMSCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsTemporaryRegistration")
                        .HasColumnType("boolean");

                    b.Property<int>("ManufactureYear")
                        .HasColumnType("integer");

                    b.Property<int>("ManufacturerId")
                        .HasColumnType("integer");

                    b.Property<int>("ModelId")
                        .HasColumnType("integer");

                    b.Property<int>("OfficeId")
                        .HasColumnType("integer");

                    b.Property<int?>("OfficerId")
                        .HasColumnType("integer");

                    b.Property<string>("OfficerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("PurchaseDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RegistrationCertificatePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SeatingCapacity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TreasuryType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("VehicleCost")
                        .HasColumnType("numeric");

                    b.Property<string>("VehicleNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VehiclePhotoPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VehicleProofUploads")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("VehicleTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("VerificationComments")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("VerificationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("VerificationStatus")
                        .HasColumnType("integer");

                    b.Property<string>("VerifierId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("DesignationId");

                    b.HasIndex("ManufacturerId");

                    b.HasIndex("ModelId");

                    b.HasIndex("OfficeId");

                    b.HasIndex("OfficerId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("VehicleTypeId");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("backend.Models.Core.VehicleTransfer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FromOfficeId")
                        .HasColumnType("integer");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ToOfficeId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TransferDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TransferOrderNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TransferOrderPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("VehicleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FromOfficeId");

                    b.HasIndex("ToOfficeId");

                    b.HasIndex("VehicleId");

                    b.ToTable("VehicleTransfers");
                });

            modelBuilder.Entity("backend.Models.Masters.Allocation", b =>
                {
                    b.Property<int>("AllocationTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("AllocationTypeId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AllocationTypeId"));

                    b.Property<string>("AllocationTypeName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("AllocationTypeName");

                    b.Property<DateTime?>("PDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("PDate");

                    b.Property<DateTime?>("TDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("TDate");

                    b.HasKey("AllocationTypeId");

                    b.ToTable("Allocations");
                });

            modelBuilder.Entity("backend.Models.Masters.Department", b =>
                {
                    b.Property<int>("DeptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("DeptId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DeptId"));

                    b.Property<string>("DeptAbbre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("DeptAbbre");

                    b.Property<string>("DeptName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("DeptName");

                    b.Property<bool?>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("Enabled");

                    b.Property<DateTime?>("PDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("PDate");

                    b.Property<DateTime?>("TDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("TDate");

                    b.HasKey("DeptId");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            DeptId = 1,
                            DeptAbbre = "AGR",
                            DeptName = "Agriculture",
                            Enabled = true,
                            PDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            DeptId = 2,
                            DeptAbbre = "AHD",
                            DeptName = "Animal Husbandry Dairy Development and Fisheries",
                            Enabled = true,
                            PDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            DeptId = 3,
                            DeptAbbre = "COP",
                            DeptName = "Cooperation",
                            Enabled = true,
                            PDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            DeptId = 4,
                            DeptAbbre = "DSW",
                            DeptName = "Defence Services Welfare",
                            Enabled = true,
                            PDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            DeptId = 5,
                            DeptAbbre = "ELE",
                            DeptName = "Elections",
                            Enabled = true,
                            PDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            DeptId = 6,
                            DeptAbbre = "EGT",
                            DeptName = "Employment Generation and Training",
                            Enabled = true,
                            PDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            DeptId = 7,
                            DeptAbbre = "ET",
                            DeptName = "Excise and Taxation",
                            Enabled = true,
                            PDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            DeptId = 8,
                            DeptAbbre = "FIN",
                            DeptName = "Finance",
                            Enabled = true,
                            PDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            DeptId = 9,
                            DeptAbbre = "FCS",
                            DeptName = "Food Civil Supplies and Consumer Affairs",
                            Enabled = true,
                            PDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            DeptId = 10,
                            DeptAbbre = "FWL",
                            DeptName = "Forest and Wild Life Preservation",
                            Enabled = true,
                            PDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            DeptId = 11,
                            DeptAbbre = "GA",
                            DeptName = "General Administration",
                            Enabled = true,
                            PDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            DeptId = 12,
                            DeptAbbre = "GR",
                            DeptName = "Governance Reforms",
                            Enabled = true,
                            PDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            DeptId = 13,
                            DeptAbbre = "HFW",
                            DeptName = "Health & Family Welfare",
                            Enabled = true,
                            PDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            DeptId = 14,
                            DeptAbbre = "HOME",
                            DeptName = "Home Affairs",
                            Enabled = true,
                            PDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            DeptId = 15,
                            DeptAbbre = "HORT",
                            DeptName = "Horticulture",
                            Enabled = true,
                            PDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            DeptId = 16,
                            DeptAbbre = "HUD",
                            DeptName = "Housing and Urban Development",
                            Enabled = true,
                            PDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            DeptId = 17,
                            DeptAbbre = "IC",
                            DeptName = "Industries and Commerce",
                            Enabled = true,
                            PDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            DeptId = 18,
                            DeptAbbre = "IPR",
                            DeptName = "Information and Public Relation",
                            Enabled = true,
                            PDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            DeptId = 19,
                            DeptAbbre = "IRR",
                            DeptName = "Irrigation",
                            Enabled = true,
                            PDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            DeptId = 20,
                            DeptAbbre = "JAIL",
                            DeptName = "Jails",
                            Enabled = true,
                            PDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            DeptId = 21,
                            DeptAbbre = "LAB",
                            DeptName = "Labour",
                            Enabled = true,
                            PDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            DeptId = 22,
                            DeptAbbre = "LLA",
                            DeptName = "Legal and Legislative Affairs",
                            Enabled = true,
                            PDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            DeptId = 23,
                            DeptAbbre = "LG",
                            DeptName = "Local Government",
                            Enabled = true,
                            PDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            DeptId = 24,
                            DeptAbbre = "LBP",
                            DeptName = "Lok Bhavan Punjab",
                            Enabled = true,
                            PDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            DeptId = 25,
                            DeptAbbre = "MER",
                            DeptName = "Medical Education and Research",
                            Enabled = true,
                            PDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            DeptId = 26,
                            DeptAbbre = "PA",
                            DeptName = "Parliamentary Affairs",
                            Enabled = true,
                            PDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            DeptId = 27,
                            DeptAbbre = "PER",
                            DeptName = "Personnel",
                            Enabled = true,
                            PDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            DeptId = 28,
                            DeptAbbre = "PLAN",
                            DeptName = "Planning",
                            Enabled = true,
                            PDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            DeptId = 29,
                            DeptAbbre = "POW",
                            DeptName = "Power",
                            Enabled = true,
                            PDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            DeptId = 30,
                            DeptAbbre = "PS",
                            DeptName = "Printing and Stationery",
                            Enabled = true,
                            PDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            DeptId = 31,
                            DeptAbbre = "PW",
                            DeptName = "Public Works",
                            Enabled = true,
                            PDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            DeptId = 32,
                            DeptAbbre = "RRD",
                            DeptName = "Revenue Rehabilitation & Disaster Management",
                            Enabled = true,
                            PDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            DeptId = 33,
                            DeptAbbre = "RDP",
                            DeptName = "Rural Development and Panchayat",
                            Enabled = true,
                            PDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            DeptId = 34,
                            DeptAbbre = "SE",
                            DeptName = "School Education",
                            Enabled = true,
                            PDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            DeptId = 35,
                            DeptAbbre = "STE",
                            DeptName = "Science, Technology & Environment",
                            Enabled = true,
                            PDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            DeptId = 36,
                            DeptAbbre = "SSW",
                            DeptName = "Social Security and Development of Women and Children",
                            Enabled = true,
                            PDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            DeptId = 37,
                            DeptAbbre = "SYS",
                            DeptName = "Sports and Youth Services",
                            Enabled = true,
                            PDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            DeptId = 38,
                            DeptAbbre = "TEI",
                            DeptName = "Technical Education and Industrial Training",
                            Enabled = true,
                            PDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            DeptId = 39,
                            DeptAbbre = "TCA",
                            DeptName = "Tourism and Cultural Affairs",
                            Enabled = true,
                            PDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            DeptId = 40,
                            DeptAbbre = "TRA",
                            DeptName = "Transport",
                            Enabled = true,
                            PDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            DeptId = 41,
                            DeptAbbre = "VIG",
                            DeptName = "Vigilance",
                            Enabled = true,
                            PDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            DeptId = 42,
                            DeptAbbre = "WSS",
                            DeptName = "Water Supply and Sanitation",
                            Enabled = true,
                            PDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            DeptId = 43,
                            DeptAbbre = "WBC",
                            DeptName = "Welfare of SCs & BCs",
                            Enabled = true,
                            PDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("backend.Models.Masters.Designation", b =>
                {
                    b.Property<int>("DesignationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("DesignationId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DesignationId"));

                    b.Property<int>("DeptId")
                        .HasColumnType("integer")
                        .HasColumnName("DeptId");

                    b.Property<string>("DesignationName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("DesignationName");

                    b.Property<string>("DesignationType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DieselFuelLimit")
                        .HasColumnType("integer")
                        .HasColumnName("DieselFuelLimit");

                    b.Property<int>("DieselMaintenanceLimit")
                        .HasColumnType("integer")
                        .HasColumnName("DieselMaintenanceLimit");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("Enabled");

                    b.Property<DateTime?>("PDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("PDate");

                    b.Property<int>("PetrolFuelLimit")
                        .HasColumnType("integer")
                        .HasColumnName("PetrolFuelLimit");

                    b.Property<int>("PetrolMaintenanceLimit")
                        .HasColumnType("integer")
                        .HasColumnName("PetrolMaintenanceLimit");

                    b.Property<DateTime?>("TDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("TDate");

                    b.HasKey("DesignationId");

                    b.HasIndex("DeptId");

                    b.ToTable("Designations");
                });

            modelBuilder.Entity("backend.Models.Masters.District", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DistAbbre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("DistAbbre");

                    b.Property<string>("DistrictName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("DistrictName");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("IsActive");

                    b.Property<DateTime?>("PDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("PDate");

                    b.Property<DateTime?>("TDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("TDate");

                    b.HasKey("Id");

                    b.ToTable("Districts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DistAbbre = "AMR",
                            DistrictName = "Amritsar",
                            IsActive = true
                        },
                        new
                        {
                            Id = 2,
                            DistAbbre = "BNA",
                            DistrictName = "Barnala",
                            IsActive = true
                        },
                        new
                        {
                            Id = 3,
                            DistAbbre = "BTI",
                            DistrictName = "Bathinda",
                            IsActive = true
                        },
                        new
                        {
                            Id = 4,
                            DistAbbre = "FDK",
                            DistrictName = "Faridkot",
                            IsActive = true
                        },
                        new
                        {
                            Id = 5,
                            DistAbbre = "FGS",
                            DistrictName = "Fatehgarh Sahib",
                            IsActive = true
                        },
                        new
                        {
                            Id = 6,
                            DistAbbre = "FZK",
                            DistrictName = "Fazilka",
                            IsActive = true
                        },
                        new
                        {
                            Id = 7,
                            DistAbbre = "FZR",
                            DistrictName = "Ferozepur",
                            IsActive = true
                        },
                        new
                        {
                            Id = 8,
                            DistAbbre = "GSP",
                            DistrictName = "Gurdaspur",
                            IsActive = true
                        },
                        new
                        {
                            Id = 9,
                            DistAbbre = "HSP",
                            DistrictName = "Hoshiarpur",
                            IsActive = true
                        },
                        new
                        {
                            Id = 10,
                            DistAbbre = "JAL",
                            DistrictName = "Jalandhar",
                            IsActive = true
                        },
                        new
                        {
                            Id = 11,
                            DistAbbre = "KPT",
                            DistrictName = "Kapurthala",
                            IsActive = true
                        },
                        new
                        {
                            Id = 12,
                            DistAbbre = "LDH",
                            DistrictName = "Ludhiana",
                            IsActive = true
                        },
                        new
                        {
                            Id = 13,
                            DistAbbre = "MKT",
                            DistrictName = "Malerkotla",
                            IsActive = true
                        },
                        new
                        {
                            Id = 14,
                            DistAbbre = "MS",
                            DistrictName = "Mansa",
                            IsActive = true
                        },
                        new
                        {
                            Id = 15,
                            DistAbbre = "MG",
                            DistrictName = "Moga",
                            IsActive = true
                        },
                        new
                        {
                            Id = 16,
                            DistAbbre = "MKS",
                            DistrictName = "Muktsar Sahib",
                            IsActive = true
                        },
                        new
                        {
                            Id = 17,
                            DistAbbre = "ND",
                            DistrictName = "New Delhi",
                            IsActive = true
                        },
                        new
                        {
                            Id = 18,
                            DistAbbre = "PTK",
                            DistrictName = "Pathankot",
                            IsActive = true
                        },
                        new
                        {
                            Id = 19,
                            DistAbbre = "PTL",
                            DistrictName = "Patiala",
                            IsActive = true
                        },
                        new
                        {
                            Id = 20,
                            DistAbbre = "RUP",
                            DistrictName = "Rupnagar",
                            IsActive = true
                        },
                        new
                        {
                            Id = 21,
                            DistAbbre = "SGR",
                            DistrictName = "Sangrur",
                            IsActive = true
                        },
                        new
                        {
                            Id = 22,
                            DistAbbre = "SAS",
                            DistrictName = "SAS Nagar (Mohali)",
                            IsActive = true
                        },
                        new
                        {
                            Id = 23,
                            DistAbbre = "SBS",
                            DistrictName = "Shaheed Bhagat Singh Nagar",
                            IsActive = true
                        },
                        new
                        {
                            Id = 24,
                            DistAbbre = "TT",
                            DistrictName = "Tarn Taran",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("backend.Models.Masters.FleetStrength", b =>
                {
                    b.Property<int>("FleetStrengthId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("FleetStrengthId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FleetStrengthId"));

                    b.Property<int>("DeptId")
                        .HasColumnType("integer")
                        .HasColumnName("DeptId");

                    b.Property<int>("DistrictId")
                        .HasColumnType("integer")
                        .HasColumnName("DistrictId");

                    b.Property<int>("FleetStrengthValue")
                        .HasColumnType("integer")
                        .HasColumnName("FleetStrength");

                    b.Property<DateTime?>("PDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("PDate");

                    b.Property<DateTime?>("TDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("TDate");

                    b.Property<int>("VehicleTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("VehicleTypeId");

                    b.HasKey("FleetStrengthId");

                    b.HasIndex("DeptId");

                    b.HasIndex("DistrictId");

                    b.HasIndex("VehicleTypeId");

                    b.ToTable("FleetStrengths");
                });

            modelBuilder.Entity("backend.Models.Masters.Manufacturer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("IsActive");

                    b.Property<string>("ManufacturerName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ManufacturerName");

                    b.Property<DateTime?>("PDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("PDate");

                    b.Property<DateTime?>("TDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("TDate");

                    b.HasKey("Id");

                    b.ToTable("Manufacturers");
                });

            modelBuilder.Entity("backend.Models.Masters.Office", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DDOCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("DDOCode");

                    b.Property<int>("DeptId")
                        .HasColumnType("integer")
                        .HasColumnName("DeptId");

                    b.Property<int>("DistrictId")
                        .HasColumnType("integer")
                        .HasColumnName("DistrictId");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("IsActive");

                    b.Property<string>("OfficeAbbreviation")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("OfficeAbbreviation");

                    b.Property<string>("OfficeAddress")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("OfficeAddress");

                    b.Property<string>("OfficeName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("OfficeName");

                    b.Property<string>("OfficeNameWithDdo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("OfficeNameWithDdo");

                    b.Property<int>("OfficeTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("OfficeTypeId");

                    b.Property<string>("OfficeTypeOther")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("OfficeTypeOther");

                    b.Property<DateTime?>("PDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("PDate");

                    b.Property<DateTime?>("TDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("TDate");

                    b.Property<int>("TehsilId")
                        .HasColumnType("integer")
                        .HasColumnName("TehsilId");

                    b.HasKey("Id");

                    b.HasIndex("DeptId");

                    b.HasIndex("DistrictId");

                    b.HasIndex("TehsilId");

                    b.ToTable("Offices");
                });

            modelBuilder.Entity("backend.Models.Masters.OfficeType", b =>
                {
                    b.Property<int>("OfficeTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("OfficeTypeId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OfficeTypeId"));

                    b.Property<string>("OfficeTypeName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("OfficeTypeName");

                    b.Property<DateTime?>("PDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("PDate");

                    b.Property<DateTime?>("TDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("TDate");

                    b.HasKey("OfficeTypeId");

                    b.ToTable("OfficeTypes");
                });

            modelBuilder.Entity("backend.Models.Masters.Officer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DeptId")
                        .HasColumnType("integer")
                        .HasColumnName("DeptId");

                    b.Property<int>("DesignationId")
                        .HasColumnType("integer")
                        .HasColumnName("DesignationId");

                    b.Property<int>("DesignationType")
                        .HasColumnType("integer")
                        .HasColumnName("DesignationType");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("Enabled");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("FileName");

                    b.Property<int>("FuelLimit")
                        .HasColumnType("integer")
                        .HasColumnName("FuelLimit");

                    b.Property<int>("FuelLimmitd")
                        .HasColumnType("integer")
                        .HasColumnName("FuelLimmitd");

                    b.Property<string>("HrmsCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("HrmsCode");

                    b.Property<int>("MaintenanceLimit")
                        .HasColumnType("integer")
                        .HasColumnName("MaintenanceLimit");

                    b.Property<int>("MaintenanceLimitd")
                        .HasColumnType("integer")
                        .HasColumnName("MaintenanceLimitd");

                    b.Property<string>("OfficerId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("OfficerId");

                    b.Property<string>("OfficerName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("OfficerName");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Remarks");

                    b.Property<DateTime?>("TDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("TDate");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("UpdatedBy");

                    b.HasKey("Id");

                    b.HasIndex("DeptId");

                    b.HasIndex("DesignationId");

                    b.ToTable("Officers");
                });

            modelBuilder.Entity("backend.Models.Masters.Project", b =>
                {
                    b.Property<int>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ProjectId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProjectId"));

                    b.Property<int>("DeptId")
                        .HasColumnType("integer")
                        .HasColumnName("DeptId");

                    b.Property<double>("FuelLitresPerMonth")
                        .HasColumnType("double precision")
                        .HasColumnName("FuelLitresPerMonth");

                    b.Property<double>("MaintenanceAmtPerAnnum")
                        .HasColumnType("double precision")
                        .HasColumnName("MaintenanceAmtPerAnnum");

                    b.Property<double>("MaintenanceAmtPerMonth")
                        .HasColumnType("double precision")
                        .HasColumnName("MaintenanceAmtPerMonth");

                    b.Property<DateTime?>("PDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("PDate");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ProjectName");

                    b.Property<DateTime?>("TDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("TDate");

                    b.HasKey("ProjectId");

                    b.HasIndex("DeptId");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            ProjectId = 1,
                            DeptId = 40,
                            FuelLitresPerMonth = 1000.0,
                            MaintenanceAmtPerAnnum = 600000.0,
                            MaintenanceAmtPerMonth = 50000.0,
                            PDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProjectName = "State Road Maintenance"
                        },
                        new
                        {
                            ProjectId = 2,
                            DeptId = 40,
                            FuelLitresPerMonth = 1500.0,
                            MaintenanceAmtPerAnnum = 900000.0,
                            MaintenanceAmtPerMonth = 75000.0,
                            PDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProjectName = "NHAI Punjab Segment"
                        },
                        new
                        {
                            ProjectId = 3,
                            DeptId = 23,
                            FuelLitresPerMonth = 800.0,
                            MaintenanceAmtPerAnnum = 480000.0,
                            MaintenanceAmtPerMonth = 40000.0,
                            PDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProjectName = "Smart City Ludhiana"
                        },
                        new
                        {
                            ProjectId = 4,
                            DeptId = 11,
                            FuelLitresPerMonth = 600.0,
                            MaintenanceAmtPerAnnum = 360000.0,
                            MaintenanceAmtPerMonth = 30000.0,
                            PDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProjectName = "Border Area Development"
                        });
                });

            modelBuilder.Entity("backend.Models.Masters.Tehsil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DistrictId")
                        .HasColumnType("integer")
                        .HasColumnName("DistrictId");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("IsActive");

                    b.Property<DateTime?>("PDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("PDate");

                    b.Property<DateTime?>("TDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("TDate");

                    b.Property<string>("TehsilName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("TehsilName");

                    b.HasKey("Id");

                    b.HasIndex("DistrictId");

                    b.ToTable("Tehsils");
                });

            modelBuilder.Entity("backend.Models.Masters.VehicleModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("IsActive");

                    b.Property<int>("ManufacturerId")
                        .HasColumnType("integer")
                        .HasColumnName("ManufacturerId");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ModelName");

                    b.Property<int>("SeatingCapacity")
                        .HasColumnType("integer")
                        .HasColumnName("SeatingCapacity");

                    b.Property<int>("VehicleTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("VehicleTypeId");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturerId");

                    b.HasIndex("VehicleTypeId");

                    b.ToTable("VehicleModels");
                });

            modelBuilder.Entity("backend.Models.Masters.VehicleType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("IsActive");

                    b.Property<DateTime?>("PDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("PDate");

                    b.Property<DateTime?>("TDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("TDate");

                    b.Property<int>("VehicleLifeKM")
                        .HasColumnType("integer")
                        .HasColumnName("VehicleLifeKM");

                    b.Property<int>("VehicleLifeYears")
                        .HasColumnType("integer")
                        .HasColumnName("VehicleLifeYears");

                    b.Property<string>("VehicleTypeExample")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("VehicleTypeExample");

                    b.Property<string>("VehicleTypeName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("VehicleTypeName");

                    b.HasKey("Id");

                    b.ToTable("VehicleTypes");
                });

            modelBuilder.Entity("backend.Models.Core.BillClaim", b =>
                {
                    b.HasOne("backend.Models.Core.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Core.VehicleInfo", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleId");

                    b.HasOne("backend.Models.Core.User", "VerifiedBy")
                        .WithMany()
                        .HasForeignKey("VerifiedById");

                    b.Navigation("CreatedBy");

                    b.Navigation("Vehicle");

                    b.Navigation("VerifiedBy");
                });

            modelBuilder.Entity("backend.Models.Core.ContractualBill", b =>
                {
                    b.HasOne("backend.Models.Core.BillClaim", "Claim")
                        .WithMany("ContractualBills")
                        .HasForeignKey("ClaimId");

                    b.HasOne("backend.Models.Core.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Claim");

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("backend.Models.Core.FuelBill", b =>
                {
                    b.HasOne("backend.Models.Core.BillClaim", "Claim")
                        .WithMany("FuelBills")
                        .HasForeignKey("ClaimId");

                    b.HasOne("backend.Models.Core.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Core.VehicleInfo", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Claim");

                    b.Navigation("CreatedBy");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("backend.Models.Core.HiredVehicleBill", b =>
                {
                    b.HasOne("backend.Models.Core.BillClaim", "Claim")
                        .WithMany("HiredVehicleBills")
                        .HasForeignKey("ClaimId");

                    b.HasOne("backend.Models.Core.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Claim");

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("backend.Models.Core.InventoryAllotment", b =>
                {
                    b.HasOne("backend.Models.Core.User", "AllottedByUser")
                        .WithMany()
                        .HasForeignKey("AllottedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Core.InventoryItem", "InventoryItem")
                        .WithMany()
                        .HasForeignKey("InventoryItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Core.VehicleInfo", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AllottedByUser");

                    b.Navigation("InventoryItem");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("backend.Models.Core.MaintenanceBill", b =>
                {
                    b.HasOne("backend.Models.Core.BillClaim", "Claim")
                        .WithMany("MaintenanceBills")
                        .HasForeignKey("ClaimId");

                    b.HasOne("backend.Models.Core.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Core.VehicleInfo", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Claim");

                    b.Navigation("CreatedBy");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("backend.Models.Core.StockTransaction", b =>
                {
                    b.HasOne("backend.Models.Core.InventoryItem", "InventoryItem")
                        .WithMany()
                        .HasForeignKey("InventoryItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Core.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InventoryItem");

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Models.Core.User", b =>
                {
                    b.HasOne("backend.Models.Masters.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentDeptId");

                    b.HasOne("backend.Models.Masters.District", "District")
                        .WithMany()
                        .HasForeignKey("DistrictId");

                    b.Navigation("Department");

                    b.Navigation("District");
                });

            modelBuilder.Entity("backend.Models.Core.UserRole", b =>
                {
                    b.HasOne("backend.Models.Core.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Core.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Models.Core.VehicleCondemnation", b =>
                {
                    b.HasOne("backend.Models.Core.VehicleInfo", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("backend.Models.Core.VehicleInfo", b =>
                {
                    b.HasOne("backend.Models.Masters.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId");

                    b.HasOne("backend.Models.Masters.Designation", "Designation")
                        .WithMany()
                        .HasForeignKey("DesignationId");

                    b.HasOne("backend.Models.Masters.Manufacturer", "Manufacturer")
                        .WithMany()
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Masters.VehicleModel", "Model")
                        .WithMany()
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Masters.Office", "Office")
                        .WithMany()
                        .HasForeignKey("OfficeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Masters.Officer", "Officer")
                        .WithMany()
                        .HasForeignKey("OfficerId");

                    b.HasOne("backend.Models.Masters.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId");

                    b.HasOne("backend.Models.Masters.VehicleType", "VehicleType")
                        .WithMany()
                        .HasForeignKey("VehicleTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Designation");

                    b.Navigation("Manufacturer");

                    b.Navigation("Model");

                    b.Navigation("Office");

                    b.Navigation("Officer");

                    b.Navigation("Project");

                    b.Navigation("VehicleType");
                });

            modelBuilder.Entity("backend.Models.Core.VehicleTransfer", b =>
                {
                    b.HasOne("backend.Models.Masters.Office", "FromOffice")
                        .WithMany()
                        .HasForeignKey("FromOfficeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Masters.Office", "ToOffice")
                        .WithMany()
                        .HasForeignKey("ToOfficeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Core.VehicleInfo", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FromOffice");

                    b.Navigation("ToOffice");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("backend.Models.Masters.Designation", b =>
                {
                    b.HasOne("backend.Models.Masters.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DeptId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("backend.Models.Masters.FleetStrength", b =>
                {
                    b.HasOne("backend.Models.Masters.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DeptId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend.Models.Masters.District", "District")
                        .WithMany()
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend.Models.Masters.VehicleType", "VehicleType")
                        .WithMany()
                        .HasForeignKey("VehicleTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("District");

                    b.Navigation("VehicleType");
                });

            modelBuilder.Entity("backend.Models.Masters.Office", b =>
                {
                    b.HasOne("backend.Models.Masters.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DeptId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend.Models.Masters.District", "District")
                        .WithMany()
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend.Models.Masters.Tehsil", "Tehsil")
                        .WithMany()
                        .HasForeignKey("TehsilId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("District");

                    b.Navigation("Tehsil");
                });

            modelBuilder.Entity("backend.Models.Masters.Officer", b =>
                {
                    b.HasOne("backend.Models.Masters.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DeptId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend.Models.Masters.Designation", "Designation")
                        .WithMany()
                        .HasForeignKey("DesignationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Designation");
                });

            modelBuilder.Entity("backend.Models.Masters.Project", b =>
                {
                    b.HasOne("backend.Models.Masters.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DeptId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("backend.Models.Masters.Tehsil", b =>
                {
                    b.HasOne("backend.Models.Masters.District", "District")
                        .WithMany()
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("District");
                });

            modelBuilder.Entity("backend.Models.Masters.VehicleModel", b =>
                {
                    b.HasOne("backend.Models.Masters.Manufacturer", "Manufacturer")
                        .WithMany()
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend.Models.Masters.VehicleType", "VehicleType")
                        .WithMany()
                        .HasForeignKey("VehicleTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Manufacturer");

                    b.Navigation("VehicleType");
                });

            modelBuilder.Entity("backend.Models.Core.BillClaim", b =>
                {
                    b.Navigation("ContractualBills");

                    b.Navigation("FuelBills");

                    b.Navigation("HiredVehicleBills");

                    b.Navigation("MaintenanceBills");
                });

            modelBuilder.Entity("backend.Models.Core.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("backend.Models.Core.User", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
