// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260506040731_UserFieldMapping")]
    partial class UserFieldMapping
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("backend.Models.Core.BillClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Comments")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedById")
                        .HasColumnType("integer");

                    b.Property<string>("FirmName")
                        .HasColumnType("text");

                    b.Property<bool>("ForwardedToTreasury")
                        .HasColumnType("boolean");

                    b.Property<string>("SanctionAuthority")
                        .HasColumnType("text");

                    b.Property<DateTime?>("SanctionOrderDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SanctionOrderNo")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("SubVoucherDescription")
                        .HasColumnType("text");

                    b.Property<string>("SubVoucherNo")
                        .HasColumnType("text");

                    b.Property<decimal>("Tax")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<int?>("VehicleId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("VerifiedById")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("VehicleId");

                    b.HasIndex("VerifiedById");

                    b.ToTable("BillClaims");
                });

            modelBuilder.Entity("backend.Models.Core.ContractualBill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("BillDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("BillNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("BillPeriodFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("BillPeriodTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ClaimId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedById")
                        .HasColumnType("integer");

                    b.Property<string>("DdoCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("VehicleNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("ClaimId");

                    b.HasIndex("CreatedById");

                    b.ToTable("ContractualBills");
                });

            modelBuilder.Entity("backend.Models.Core.FuelBill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("BillDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("BillNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("ClaimId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedById")
                        .HasColumnType("integer");

                    b.Property<decimal>("FuelQuantity")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("NocExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NocFile")
                        .HasColumnType("text");

                    b.Property<DateTime?>("NocIssueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("OdometerReading")
                        .HasColumnType("integer");

                    b.Property<string>("SanctionPermissionFile")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("VehicleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClaimId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("VehicleId");

                    b.ToTable("FuelBills");
                });

            modelBuilder.Entity("backend.Models.Core.HiredVehicleBill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("BillDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("BillNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("ClaimId")
                        .HasColumnType("integer");

                    b.Property<string>("ContractorName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ContractorPhone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedById")
                        .HasColumnType("integer");

                    b.Property<DateTime>("HiredFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("HiredTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("KmCovered")
                        .HasColumnType("integer");

                    b.Property<int>("NoOfVehicles")
                        .HasColumnType("integer");

                    b.Property<string>("OfficeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("VehicleNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("VehicleType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("ClaimId");

                    b.HasIndex("CreatedById");

                    b.ToTable("HiredVehicleBills");
                });

            modelBuilder.Entity("backend.Models.Core.InventoryAllotment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AllotmentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("AllottedByUserId")
                        .HasColumnType("integer");

                    b.Property<int>("InventoryItemId")
                        .HasColumnType("integer");

                    b.Property<string>("OdometerReading")
                        .HasColumnType("text");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<string>("Remarks")
                        .HasColumnType("text");

                    b.Property<int>("VehicleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AllottedByUserId");

                    b.HasIndex("InventoryItemId");

                    b.HasIndex("VehicleId");

                    b.ToTable("InventoryAllotments");
                });

            modelBuilder.Entity("backend.Models.Core.InventoryItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("InventoryItems");
                });

            modelBuilder.Entity("backend.Models.Core.MaintenanceBill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("BillDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("BillNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("ClaimId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedById")
                        .HasColumnType("integer");

                    b.Property<string>("Details")
                        .HasColumnType("text");

                    b.Property<string>("MaintenanceType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("OdometerReading")
                        .HasColumnType("integer");

                    b.Property<string>("SanctionPermissionFile")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("VehicleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClaimId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("VehicleId");

                    b.ToTable("MaintenanceBills");
                });

            modelBuilder.Entity("backend.Models.Core.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Drawing & Disbursing Officer (Maker)",
                            Name = "DDO"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Administrator (Checker)",
                            Name = "ADMN"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Nodal Officer (Verifier)",
                            Name = "NDOF"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Secretary",
                            Name = "SEC"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Head of Department",
                            Name = "HOD"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "District Collector",
                            Name = "DCL"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Finance Department",
                            Name = "FD"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Petrol Pump Officer",
                            Name = "PPOF"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Guest User (OTP Login)",
                            Name = "GUEST"
                        });
                });

            modelBuilder.Entity("backend.Models.Core.StockTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("BillDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("BillNumber")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("InventoryItemId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<string>("Remarks")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("InventoryItemId");

                    b.HasIndex("UserId");

                    b.ToTable("StockTransactions");
                });

            modelBuilder.Entity("backend.Models.Core.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("UserId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedDate");

                    b.Property<string>("DDOCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("DepartmentDeptId")
                        .HasColumnType("integer");

                    b.Property<int?>("DeptId")
                        .HasColumnType("integer")
                        .HasColumnName("DeptId");

                    b.Property<int?>("DistrictId")
                        .HasColumnType("integer");

                    b.Property<string>("EmailId")
                        .HasColumnType("text")
                        .HasColumnName("EmailId");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("Enabled");

                    b.Property<int>("FailedAttempts")
                        .HasColumnType("integer");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<bool>("IsGuest")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsNonTreasuryDDO")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LockUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ManagedDdos")
                        .HasColumnType("text");

                    b.Property<string>("MiddleName")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNo")
                        .HasColumnType("text")
                        .HasColumnName("PhoneNo");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.HasIndex("DepartmentDeptId");

                    b.HasIndex("DistrictId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("backend.Models.Core.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("backend.Models.Core.VehicleCondemnation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("AuctionAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("AuctionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AuctionStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CondemnationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CondemnationOrderNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CondemnationOrderPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("VehicleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("VehicleId");

                    b.ToTable("VehicleCondemnations");
                });

            modelBuilder.Entity("backend.Models.Core.VehicleInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AllocationType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContractorContactNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContractorName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrentStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DDOCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("integer");

                    b.Property<int?>("DesignationId")
                        .HasColumnType("integer");

                    b.Property<string>("DriverContactNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DriverName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DriverType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EngineChasisNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FdApprovalPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FleetStrengthLetterPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FuelUsed")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HRMSCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsTemporaryRegistration")
                        .HasColumnType("boolean");

                    b.Property<int>("ManufactureYear")
                        .HasColumnType("integer");

                    b.Property<int>("ManufacturerId")
                        .HasColumnType("integer");

                    b.Property<int>("ModelId")
                        .HasColumnType("integer");

                    b.Property<int>("OfficeId")
                        .HasColumnType("integer");

                    b.Property<int?>("OfficerId")
                        .HasColumnType("integer");

                    b.Property<string>("OfficerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("PurchaseDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RegistrationCertificatePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SeatingCapacity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TreasuryType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("VehicleCost")
                        .HasColumnType("numeric");

                    b.Property<string>("VehicleNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VehiclePhotoPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VehicleProofUploads")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("VehicleTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("VerificationComments")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("VerificationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("VerificationStatus")
                        .HasColumnType("integer");

                    b.Property<string>("VerifierId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("DesignationId");

                    b.HasIndex("ManufacturerId");

                    b.HasIndex("ModelId");

                    b.HasIndex("OfficeId");

                    b.HasIndex("OfficerId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("VehicleTypeId");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("backend.Models.Core.VehicleTransfer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FromOfficeId")
                        .HasColumnType("integer");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ToOfficeId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TransferDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TransferOrderNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TransferOrderPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("VehicleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FromOfficeId");

                    b.HasIndex("ToOfficeId");

                    b.HasIndex("VehicleId");

                    b.ToTable("VehicleTransfers");
                });

            modelBuilder.Entity("backend.Models.Masters.Department", b =>
                {
                    b.Property<int>("DeptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("DeptId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DeptId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedDate");

                    b.Property<string>("DepartmentCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("DepartmentCode");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("DepartmentName");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("Enabled");

                    b.HasKey("DeptId");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            DeptId = 1,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentCode = "AGR",
                            DepartmentName = "Agriculture",
                            Enabled = true
                        },
                        new
                        {
                            DeptId = 2,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentCode = "AHD",
                            DepartmentName = "Animal Husbandry Dairy Development and Fisheries",
                            Enabled = true
                        },
                        new
                        {
                            DeptId = 3,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentCode = "COP",
                            DepartmentName = "Cooperation",
                            Enabled = true
                        },
                        new
                        {
                            DeptId = 4,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentCode = "DSW",
                            DepartmentName = "Defence Services Welfare",
                            Enabled = true
                        },
                        new
                        {
                            DeptId = 5,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentCode = "ELE",
                            DepartmentName = "Elections",
                            Enabled = true
                        },
                        new
                        {
                            DeptId = 6,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentCode = "EGT",
                            DepartmentName = "Employment Generation and Training",
                            Enabled = true
                        },
                        new
                        {
                            DeptId = 7,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentCode = "ET",
                            DepartmentName = "Excise and Taxation",
                            Enabled = true
                        },
                        new
                        {
                            DeptId = 8,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentCode = "FIN",
                            DepartmentName = "Finance",
                            Enabled = true
                        },
                        new
                        {
                            DeptId = 9,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentCode = "FCS",
                            DepartmentName = "Food Civil Supplies and Consumer Affairs",
                            Enabled = true
                        },
                        new
                        {
                            DeptId = 10,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentCode = "FWL",
                            DepartmentName = "Forest and Wild Life Preservation",
                            Enabled = true
                        },
                        new
                        {
                            DeptId = 11,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentCode = "GA",
                            DepartmentName = "General Administration",
                            Enabled = true
                        },
                        new
                        {
                            DeptId = 12,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentCode = "GR",
                            DepartmentName = "Governance Reforms",
                            Enabled = true
                        },
                        new
                        {
                            DeptId = 13,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentCode = "HFW",
                            DepartmentName = "Health & Family Welfare",
                            Enabled = true
                        },
                        new
                        {
                            DeptId = 14,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentCode = "HOME",
                            DepartmentName = "Home Affairs",
                            Enabled = true
                        },
                        new
                        {
                            DeptId = 15,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentCode = "HORT",
                            DepartmentName = "Horticulture",
                            Enabled = true
                        },
                        new
                        {
                            DeptId = 16,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentCode = "HUD",
                            DepartmentName = "Housing and Urban Development",
                            Enabled = true
                        },
                        new
                        {
                            DeptId = 17,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentCode = "IC",
                            DepartmentName = "Industries and Commerce",
                            Enabled = true
                        },
                        new
                        {
                            DeptId = 18,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentCode = "IPR",
                            DepartmentName = "Information and Public Relation",
                            Enabled = true
                        },
                        new
                        {
                            DeptId = 19,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentCode = "IRR",
                            DepartmentName = "Irrigation",
                            Enabled = true
                        },
                        new
                        {
                            DeptId = 20,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentCode = "JAIL",
                            DepartmentName = "Jails",
                            Enabled = true
                        },
                        new
                        {
                            DeptId = 21,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentCode = "LAB",
                            DepartmentName = "Labour",
                            Enabled = true
                        },
                        new
                        {
                            DeptId = 22,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentCode = "LLA",
                            DepartmentName = "Legal and Legislative Affairs",
                            Enabled = true
                        },
                        new
                        {
                            DeptId = 23,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentCode = "LG",
                            DepartmentName = "Local Government",
                            Enabled = true
                        },
                        new
                        {
                            DeptId = 24,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentCode = "LBP",
                            DepartmentName = "Lok Bhavan Punjab",
                            Enabled = true
                        },
                        new
                        {
                            DeptId = 25,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentCode = "MER",
                            DepartmentName = "Medical Education and Research",
                            Enabled = true
                        },
                        new
                        {
                            DeptId = 26,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentCode = "PA",
                            DepartmentName = "Parliamentary Affairs",
                            Enabled = true
                        },
                        new
                        {
                            DeptId = 27,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentCode = "PER",
                            DepartmentName = "Personnel",
                            Enabled = true
                        },
                        new
                        {
                            DeptId = 28,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentCode = "PLAN",
                            DepartmentName = "Planning",
                            Enabled = true
                        },
                        new
                        {
                            DeptId = 29,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentCode = "POW",
                            DepartmentName = "Power",
                            Enabled = true
                        },
                        new
                        {
                            DeptId = 30,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentCode = "PS",
                            DepartmentName = "Printing and Stationery",
                            Enabled = true
                        },
                        new
                        {
                            DeptId = 31,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentCode = "PW",
                            DepartmentName = "Public Works",
                            Enabled = true
                        },
                        new
                        {
                            DeptId = 32,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentCode = "RRD",
                            DepartmentName = "Revenue Rehabilitation & Disaster Management",
                            Enabled = true
                        },
                        new
                        {
                            DeptId = 33,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentCode = "RDP",
                            DepartmentName = "Rural Development and Panchayat",
                            Enabled = true
                        },
                        new
                        {
                            DeptId = 34,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentCode = "SE",
                            DepartmentName = "School Education",
                            Enabled = true
                        },
                        new
                        {
                            DeptId = 35,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentCode = "STE",
                            DepartmentName = "Science, Technology & Environment",
                            Enabled = true
                        },
                        new
                        {
                            DeptId = 36,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentCode = "SSW",
                            DepartmentName = "Social Security and Development of Women and Children",
                            Enabled = true
                        },
                        new
                        {
                            DeptId = 37,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentCode = "SYS",
                            DepartmentName = "Sports and Youth Services",
                            Enabled = true
                        },
                        new
                        {
                            DeptId = 38,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentCode = "TEI",
                            DepartmentName = "Technical Education and Industrial Training",
                            Enabled = true
                        },
                        new
                        {
                            DeptId = 39,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentCode = "TCA",
                            DepartmentName = "Tourism and Cultural Affairs",
                            Enabled = true
                        },
                        new
                        {
                            DeptId = 40,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentCode = "TRA",
                            DepartmentName = "Transport",
                            Enabled = true
                        },
                        new
                        {
                            DeptId = 41,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentCode = "VIG",
                            DepartmentName = "Vigilance",
                            Enabled = true
                        },
                        new
                        {
                            DeptId = 42,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentCode = "WSS",
                            DepartmentName = "Water Supply and Sanitation",
                            Enabled = true
                        },
                        new
                        {
                            DeptId = 43,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentCode = "WBC",
                            DepartmentName = "Welfare of SCs & BCs",
                            Enabled = true
                        });
                });

            modelBuilder.Entity("backend.Models.Masters.Designation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("integer");

                    b.Property<string>("DesignationType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("DieselFuelLimit")
                        .HasColumnType("numeric");

                    b.Property<decimal>("DieselMaintenanceLimit")
                        .HasColumnType("numeric");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PetrolFuelLimit")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PetrolMaintenanceLimit")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Designations");
                });

            modelBuilder.Entity("backend.Models.Masters.District", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Districts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "ASR",
                            IsActive = true,
                            Name = "Amritsar"
                        },
                        new
                        {
                            Id = 2,
                            Code = "BNL",
                            IsActive = true,
                            Name = "Barnala"
                        },
                        new
                        {
                            Id = 3,
                            Code = "BTI",
                            IsActive = true,
                            Name = "Bathinda"
                        },
                        new
                        {
                            Id = 4,
                            Code = "CH",
                            IsActive = true,
                            Name = "Chandigarh"
                        },
                        new
                        {
                            Id = 5,
                            Code = "FDK",
                            IsActive = true,
                            Name = "Faridkot"
                        },
                        new
                        {
                            Id = 6,
                            Code = "FGS",
                            IsActive = true,
                            Name = "Fatehgarh Sahib"
                        },
                        new
                        {
                            Id = 7,
                            Code = "FZK",
                            IsActive = true,
                            Name = "Fazilka"
                        },
                        new
                        {
                            Id = 8,
                            Code = "FZR",
                            IsActive = true,
                            Name = "Ferozepur"
                        },
                        new
                        {
                            Id = 9,
                            Code = "GSP",
                            IsActive = true,
                            Name = "Gurdaspur"
                        },
                        new
                        {
                            Id = 10,
                            Code = "HSP",
                            IsActive = true,
                            Name = "Hoshiarpur"
                        },
                        new
                        {
                            Id = 11,
                            Code = "JAL",
                            IsActive = true,
                            Name = "Jalandhar"
                        },
                        new
                        {
                            Id = 12,
                            Code = "KPT",
                            IsActive = true,
                            Name = "Kapurthala"
                        },
                        new
                        {
                            Id = 13,
                            Code = "LDH",
                            IsActive = true,
                            Name = "Ludhiana"
                        },
                        new
                        {
                            Id = 14,
                            Code = "MKT",
                            IsActive = true,
                            Name = "Malerkotla"
                        },
                        new
                        {
                            Id = 15,
                            Code = "MS",
                            IsActive = true,
                            Name = "Mansa"
                        },
                        new
                        {
                            Id = 16,
                            Code = "MG",
                            IsActive = true,
                            Name = "Moga"
                        },
                        new
                        {
                            Id = 17,
                            Code = "MKS",
                            IsActive = true,
                            Name = "Muktsar Sahib"
                        },
                        new
                        {
                            Id = 18,
                            Code = "ND",
                            IsActive = true,
                            Name = "New Delhi"
                        },
                        new
                        {
                            Id = 19,
                            Code = "PTK",
                            IsActive = true,
                            Name = "Pathankot"
                        },
                        new
                        {
                            Id = 20,
                            Code = "PTL",
                            IsActive = true,
                            Name = "Patiala"
                        },
                        new
                        {
                            Id = 21,
                            Code = "RUP",
                            IsActive = true,
                            Name = "Rupnagar"
                        },
                        new
                        {
                            Id = 22,
                            Code = "SGR",
                            IsActive = true,
                            Name = "Sangrur"
                        },
                        new
                        {
                            Id = 23,
                            Code = "SAS",
                            IsActive = true,
                            Name = "SAS Nagar (Mohali)"
                        },
                        new
                        {
                            Id = 24,
                            Code = "SBS",
                            IsActive = true,
                            Name = "Shaheed Bhagat Singh Nagar"
                        },
                        new
                        {
                            Id = 25,
                            Code = "TT",
                            IsActive = true,
                            Name = "Tarn Taran"
                        });
                });

            modelBuilder.Entity("backend.Models.Masters.Manufacturer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Manufacturers");
                });

            modelBuilder.Entity("backend.Models.Masters.Office", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DDOCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("integer");

                    b.Property<int>("DistrictId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("TehsilId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("DistrictId");

                    b.HasIndex("TehsilId");

                    b.ToTable("Offices");
                });

            modelBuilder.Entity("backend.Models.Masters.Officer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("DesignationId")
                        .HasColumnType("integer");

                    b.Property<decimal>("DieselFuelLimit")
                        .HasColumnType("numeric");

                    b.Property<decimal>("DieselMaintenanceLimit")
                        .HasColumnType("numeric");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HRMSCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("OfficeId")
                        .HasColumnType("integer");

                    b.Property<decimal>("PetrolFuelLimit")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PetrolMaintenanceLimit")
                        .HasColumnType("numeric");

                    b.Property<string>("Remarks")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DesignationId");

                    b.HasIndex("OfficeId");

                    b.ToTable("Officers");
                });

            modelBuilder.Entity("backend.Models.Masters.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("PetrolFuelLimit")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PetrolMaintenanceLimit")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = 40,
                            IsActive = true,
                            Name = "State Road Maintenance",
                            PetrolFuelLimit = 0m,
                            PetrolMaintenanceLimit = 0m
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = 40,
                            IsActive = true,
                            Name = "NHAI Punjab Segment",
                            PetrolFuelLimit = 0m,
                            PetrolMaintenanceLimit = 0m
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = 23,
                            IsActive = true,
                            Name = "Smart City Ludhiana",
                            PetrolFuelLimit = 0m,
                            PetrolMaintenanceLimit = 0m
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = 11,
                            IsActive = true,
                            Name = "Border Area Development",
                            PetrolFuelLimit = 0m,
                            PetrolMaintenanceLimit = 0m
                        });
                });

            modelBuilder.Entity("backend.Models.Masters.Tehsil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DistrictId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DistrictId");

                    b.ToTable("Tehsils");
                });

            modelBuilder.Entity("backend.Models.Masters.VehicleModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("ManufacturerId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SeatingCapacity")
                        .HasColumnType("integer");

                    b.Property<string>("VehicleType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturerId");

                    b.ToTable("VehicleModels");
                });

            modelBuilder.Entity("backend.Models.Masters.VehicleType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("VehicleTypes");
                });

            modelBuilder.Entity("backend.Models.Core.BillClaim", b =>
                {
                    b.HasOne("backend.Models.Core.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Core.VehicleInfo", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleId");

                    b.HasOne("backend.Models.Core.User", "VerifiedBy")
                        .WithMany()
                        .HasForeignKey("VerifiedById");

                    b.Navigation("CreatedBy");

                    b.Navigation("Vehicle");

                    b.Navigation("VerifiedBy");
                });

            modelBuilder.Entity("backend.Models.Core.ContractualBill", b =>
                {
                    b.HasOne("backend.Models.Core.BillClaim", "Claim")
                        .WithMany("ContractualBills")
                        .HasForeignKey("ClaimId");

                    b.HasOne("backend.Models.Core.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Claim");

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("backend.Models.Core.FuelBill", b =>
                {
                    b.HasOne("backend.Models.Core.BillClaim", "Claim")
                        .WithMany("FuelBills")
                        .HasForeignKey("ClaimId");

                    b.HasOne("backend.Models.Core.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Core.VehicleInfo", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Claim");

                    b.Navigation("CreatedBy");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("backend.Models.Core.HiredVehicleBill", b =>
                {
                    b.HasOne("backend.Models.Core.BillClaim", "Claim")
                        .WithMany("HiredVehicleBills")
                        .HasForeignKey("ClaimId");

                    b.HasOne("backend.Models.Core.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Claim");

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("backend.Models.Core.InventoryAllotment", b =>
                {
                    b.HasOne("backend.Models.Core.User", "AllottedByUser")
                        .WithMany()
                        .HasForeignKey("AllottedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Core.InventoryItem", "InventoryItem")
                        .WithMany()
                        .HasForeignKey("InventoryItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Core.VehicleInfo", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AllottedByUser");

                    b.Navigation("InventoryItem");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("backend.Models.Core.MaintenanceBill", b =>
                {
                    b.HasOne("backend.Models.Core.BillClaim", "Claim")
                        .WithMany("MaintenanceBills")
                        .HasForeignKey("ClaimId");

                    b.HasOne("backend.Models.Core.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Core.VehicleInfo", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Claim");

                    b.Navigation("CreatedBy");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("backend.Models.Core.StockTransaction", b =>
                {
                    b.HasOne("backend.Models.Core.InventoryItem", "InventoryItem")
                        .WithMany()
                        .HasForeignKey("InventoryItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Core.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InventoryItem");

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Models.Core.User", b =>
                {
                    b.HasOne("backend.Models.Masters.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentDeptId");

                    b.HasOne("backend.Models.Masters.District", "District")
                        .WithMany()
                        .HasForeignKey("DistrictId");

                    b.Navigation("Department");

                    b.Navigation("District");
                });

            modelBuilder.Entity("backend.Models.Core.UserRole", b =>
                {
                    b.HasOne("backend.Models.Core.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Core.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Models.Core.VehicleCondemnation", b =>
                {
                    b.HasOne("backend.Models.Core.VehicleInfo", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("backend.Models.Core.VehicleInfo", b =>
                {
                    b.HasOne("backend.Models.Masters.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId");

                    b.HasOne("backend.Models.Masters.Designation", "Designation")
                        .WithMany()
                        .HasForeignKey("DesignationId");

                    b.HasOne("backend.Models.Masters.Manufacturer", "Manufacturer")
                        .WithMany()
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Masters.VehicleModel", "Model")
                        .WithMany()
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Masters.Office", "Office")
                        .WithMany()
                        .HasForeignKey("OfficeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Masters.Officer", "Officer")
                        .WithMany()
                        .HasForeignKey("OfficerId");

                    b.HasOne("backend.Models.Masters.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId");

                    b.HasOne("backend.Models.Masters.VehicleType", "VehicleType")
                        .WithMany()
                        .HasForeignKey("VehicleTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Designation");

                    b.Navigation("Manufacturer");

                    b.Navigation("Model");

                    b.Navigation("Office");

                    b.Navigation("Officer");

                    b.Navigation("Project");

                    b.Navigation("VehicleType");
                });

            modelBuilder.Entity("backend.Models.Core.VehicleTransfer", b =>
                {
                    b.HasOne("backend.Models.Masters.Office", "FromOffice")
                        .WithMany()
                        .HasForeignKey("FromOfficeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Masters.Office", "ToOffice")
                        .WithMany()
                        .HasForeignKey("ToOfficeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Core.VehicleInfo", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FromOffice");

                    b.Navigation("ToOffice");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("backend.Models.Masters.Designation", b =>
                {
                    b.HasOne("backend.Models.Masters.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("backend.Models.Masters.Office", b =>
                {
                    b.HasOne("backend.Models.Masters.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Masters.District", "District")
                        .WithMany()
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Masters.Tehsil", "Tehsil")
                        .WithMany()
                        .HasForeignKey("TehsilId");

                    b.Navigation("Department");

                    b.Navigation("District");

                    b.Navigation("Tehsil");
                });

            modelBuilder.Entity("backend.Models.Masters.Officer", b =>
                {
                    b.HasOne("backend.Models.Masters.Designation", "Designation")
                        .WithMany()
                        .HasForeignKey("DesignationId");

                    b.HasOne("backend.Models.Masters.Office", "Office")
                        .WithMany()
                        .HasForeignKey("OfficeId");

                    b.Navigation("Designation");

                    b.Navigation("Office");
                });

            modelBuilder.Entity("backend.Models.Masters.Project", b =>
                {
                    b.HasOne("backend.Models.Masters.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("backend.Models.Masters.Tehsil", b =>
                {
                    b.HasOne("backend.Models.Masters.District", "District")
                        .WithMany()
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("District");
                });

            modelBuilder.Entity("backend.Models.Masters.VehicleModel", b =>
                {
                    b.HasOne("backend.Models.Masters.Manufacturer", "Manufacturer")
                        .WithMany()
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manufacturer");
                });

            modelBuilder.Entity("backend.Models.Core.BillClaim", b =>
                {
                    b.Navigation("ContractualBills");

                    b.Navigation("FuelBills");

                    b.Navigation("HiredVehicleBills");

                    b.Navigation("MaintenanceBills");
                });

            modelBuilder.Entity("backend.Models.Core.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("backend.Models.Core.User", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
